const actresses = [
  "Abella Danger",
  "Angela White",
  "Mia Malkova",
  "Riley Reid",
  "Lana Rhoades",
  "Lisa Ann",
  "Jenna Jameson",
  "Sasha Grey",
  "Eva Elfie",
  "Emily Willis",
  "Adriana Chechik",
  "Dani Daniels",
  "Elsa Jean",
  "Kendra Sunderland",
  "Nicole Aniston",
  "Brandi Love",
  "Kendra Lust",
  "Violet Myers",
  "Mia Khalifa",
  "Dillion Harper",
  "Gina Valentina",
  "Alexis Texas",
  "Ava Addams",
  "Katie Kush",
  "Piper Perri",
  "Elsa Jean",
  "Jasmine Sherni",
  "Jade Kush",
  "Lena Paul",
  "Molly Little",
  "Sky Bri",
  "Nina North",
  "Autumn Falls",
  "Kira Noir",
  "Ella Knox",
  "Kylie Rocket",
  "Vanna Bardot",
  "Jane Wilde",
  "Natalia Starr",
  "Megan Rain",
  "Abigail Mac",
  "Aaliyah Love",
  "Alina Lopez",
  "Ariana Marie",
  "Brianna Beach",
  "Carmen Caliente",
  "Casey Calvert",
  "Cherie DeVille",
  "Christen Courtney",
  "Coco Lovelock",
  "Daisy Stone",
  "Gia Derza",
  "Isiah Maxwell",
  "Jillian Janson",
  "Julia Ann",
  "Kali Roses",
  "Katrina Jade",
  "Kenzie Reeves",
  "Leah Gotti",
  "Lexi Luna",
  "Lily Lou",
  "Mandy Muse",
  "Marley Brinx",
  "Maya Bijou",
  "Mia Evans",
  "Mia Li",
  "Monique Alexander",
  "Natalie Brooks",
  "Nikki Benz",
  "Olivia Austin",
  "Penny Pax",
  "Rachel Starr",
  "Rebecca Volpetti",
  "Remy LaCroix",
  "Romi Rain",
  "Sabrina Banks",
  "Sarah Vandella",
  "Serena Blair",
  "Sinn Sage",
  "Siri Dahl",
  "Sophia Leone",
  "Stella Cox",
  "Tanya Tate",
  "Tasha Reign",
  "Teal Conrad",
  "Tiffany Watson",
  "Valentina Nappi",
  "Veronica Avluv",
  "Victoria June",
  "Wifey",
  "Wendy Moon",
  "Whitney Wright",
  "Xandra Sixx",
  "Yhivi",
  "Zoe Bloom",
  "Aubrey Sinclair",
  "Bunny Colby",
  "Carmen Electra",
  "Demi Sutra",
  "Erica Lauren",
  "Faye Reagan"
];

const profiles = {};

actresses.forEach((name, index) => {
  profiles[name] = {
    id: index + 1,
    name: name,
    photo: "",
    description: "Описание пока не добавлено.",
    debut: "Не указано",
    collaborations: "Не указано",
    websites: "",
    country: "Не указано",
    interests: "Не указано",
    style: "Дружелюбный",
    greeting: `Привет! Это виртуальный профиль ${name}.`,
    messages: []
  };
});

let favorites =
  JSON.parse(localStorage.getItem("favorites") || "[]");
